version = 1

[[annotations]]
path = ".github/**"
SPDX-FileCopyrightText = "2024-2025 Amilcar Lucas"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ".vscode/*"
SPDX-FileCopyrightText = "2024-2025 Amilcar Lucas"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "ardupilot_methodic_configurator/vehicle_templates/**"
SPDX-FileCopyrightText = "2024-2025 Amilcar Lucas"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "images/**"
SPDX-FileCopyrightText = "2024-2025 Amilcar Lucas"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [".coveragerc", ".gitignore", ".markdown-link-check.json", ".markdownlint.yaml", ".pre-commit-config.yaml", ".pylintrc"]
SPDX-FileCopyrightText = "2024-2025 Amilcar Lucas"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["24_inflight_magnetometer_fit_setup.pdef.xml", "REUSE.toml", "SECURITY.md", "SetupDeveloperPC.bat", "SetupDeveloperPC.sh"]
SPDX-FileCopyrightText = "2024-2025 Amilcar Lucas"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["ardupilot_methodic_configurator/*.png", "ardupilot_methodic_configurator/configuration_steps_*.json"]
SPDX-FileCopyrightText = "2024-2025 Amilcar Lucas"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["ardupilot_methodic_configurator/locale/**"]
SPDX-FileCopyrightText = "2024-2025 Amilcar Lucas"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["ardupilot_methodic_configurator/locale/zh_CN/**"]
precedence = "override"
SPDX-FileCopyrightText = "2024 SakuraRC_Yang <35626190+BloodSakura3774@users.noreply.github.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["cliff.toml", "install_msgfmt.bat", "install_wsl.bash", "package.bat", "pyproject.toml", "pytest.ini", "test_pip_package.sh"]
SPDX-FileCopyrightText = "2024-2025 Amilcar Lucas"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "credits/Python_Tkinter_ComboBox-Mozilla_Public_License_version_2.0.html"
SPDX-FileCopyrightText = "geraldew"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = "credits/Scrollable_TK_frame-Mozilla_Public_License_version_2.0.html"
SPDX-FileCopyrightText = "Mark Pointing"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = ["credits/certifi-LICENSE", "credits/python-certifi-LICENSE"]
SPDX-FileCopyrightText = "certifi developers"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = "credits/ArduPilot_tempcal_IMU.py-COPYING.txt"
SPDX-FileCopyrightText = "2024-2025 Amilcar Lucas"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "credits/charset-normalizer-LICENSE"
SPDX-FileCopyrightText = "Copyright (c) 2019 TAHRI Ahmed R."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "credits/future-LICENSE.txt"
SPDX-FileCopyrightText = "Copyright (c) 2013-2024 Python Charmers, Australia"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "credits/idna-LICENSE.md"
SPDX-FileCopyrightText = "Copyright (c) 2013-2024, Kim Davies and contributors"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "credits/lxml-LICENSE.txt"
SPDX-FileCopyrightText = "Copyright (c) 2004 Infrae. All rights reserved."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "credits/platformdirs-LICENSE"
SPDX-FileCopyrightText = "Copyright (c) 2010-202x The platformdirs developers"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "credits/pymavlink-COPYING"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "credits/python-future-LICENSE.txt"
SPDX-FileCopyrightText = "Copyright (c) 2013-2024 Python Charmers, Australia"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "credits/urllib3-LICENSE.txt"
SPDX-FileCopyrightText = "Copyright (c) 2008-2020 Andrey Petrov and contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["windows/ardupilot_methodic_configurator*", "windows/settings_template.json"]
SPDX-FileCopyrightText = "2024-2025 Amilcar Lucas"
SPDX-License-Identifier = "GPL-3.0-or-later"
