exclude = [
    ".git",
    "__pycache__",
    "__target__",
    "dist",
]

lint.select = [
    "F",    # pycodestyle
    "E",    # Pyflakes
    "W",    # Warnings
    "U",    # pyupgrade
    "I",    # isort
    "N",    # pep8-naming
    "PL",   # Pylint
    "B",    # flake8-bugbear
    "RUF",  # Ruff-specific codes
    "PERF", # Performance-related issues
    "SIM",  # flake8-simplify
    "LOG",  # flake8-logging
    "G",    #  flake8-logging-format
    #"C901", # maccabe
    "S",    # flake8-bandit
    "TID",  # flake8-tidy-imports
    "TCH",  # flake8-type-checking
    "INT",  # flake8-gettext
    "FLY002", # flynt
    #"FURB", # refurb
    "ISC",  # flake8-implicit-str-concat
    "ICN",  # flake8-import-conventions
]

lint.ignore = [
    "PLR0911",  # too many return statements
    "PLR0912",  # too many branches
    "PLR0913",  # too many arguments
    "PLR0915",  # too many statements
    "PLR2004",  # Magic value used in comparison, consider replacing `X` with a constant variable
    "PLW0603",  # Using the global statement to update `X` is discouraged
    "PLW2901",  # `for` loop variable `X` overwritten by assignment target
    "PERF203",  # `try`-`except` within a loop incurs performance overhead
    "SIM115",  # Use context handler for opening files
    "N801",    # Class name `FTP_OP` should use CapWords convention
    "N802",    # Function name `X` should be lowercase
    "N806",    # Variable name `X` should be lowercase
    "N812",    # Lowercase `x` imported as non-lowercase `X`
    "N814",    # Camelcase `X` imported as constant `Y`
    "N817",    # CamelCase `X` imported as acronym `Y`
    "N999",    # Invalid module name: 'MethodicConfigurator'
]

line-length = 127
indent-width = 4

target-version = "py38"