exclude = [
    ".git",
    "__pycache__",
    "__target__",
    "dist",
]

lint.select = [
    "F",    # pycodestyle
    "E",    # Pyflakes
    "W",    # Warnings
    "U",    # pyupgrade
    "I",    # isort
    "PL",   # Pylint
    "B",    # flake8-bugbear
    "RUF",  # Ruff-specific codes
    "PERF", # Performance-related issues
    "SIM",  # flake8-simplify
    "LOG",  # Logging issues
]

lint.ignore = [
    "PLR0911",  # too many return statements
    "PLR0912",  # too many branches
    "PLR0913",  # too many arguments
    "PLR0915",  # too many statements
    "PLR2004",  # Magic value used in comparison, consider replacing `X` with a constant variable
    "PLW0603",  # Using the global statement to update `X` is discouraged
    "PLW2901",  # `for` loop variable `X` overwritten by assignment target
    "PERF203",  # `try`-`except` within a loop incurs performance overhead
    "SIM115",  # Use context handler for opening files
]

line-length = 127
indent-width = 4

target-version = "py38"