"""
Compatibility support for the MAVLink PARAM_ERROR message.

This file is part of ArduPilot Methodic Configurator. https://github.com/ArduPilot/MethodicConfigurator

SPDX-FileCopyrightText: 2026 Amilcar do Carmo Lucas <amilcar.lucas@iav.de>

SPDX-License-Identifier: GPL-3.0-or-later
"""

import struct
from os import environ
from typing import ClassVar

from pymavlink import mavutil

PARAM_ERROR_MESSAGE_ID = 345


def install_param_error_message() -> None:
    """
    Register the MAVLink-2 PARAM_ERROR decoder when pymavlink does not provide it.

    PARAM_ERROR is currently a MAVLink work-in-progress message. ArduPilot uses it to
    reject invalid ``PARAM_SET`` requests, but pymavlink 2.4.49 does not yet generate
    a decoder for it. Registering the definition here lets pymavlink validate its CRC
    and decode the message without changing the project's pinned dependency.

    This definition is generated from MAVLink common.xml message 345:
    https://github.com/mavlink/mavlink/blob/master/message_definitions/v1.0/common.xml
    (the message is marked WIP there).  It was verified against pymavlink
    snapshot 002ddac8c1741f9027e0fb1e11c4ad0cb31bdea0: message id 345,
    CRC extra 209, and payload layout ``<hBB16sB``.  If a dialect already
    provides this message, its generated decoder is retained.

    """
    # PARAM_ERROR's id (345) requires MAVLink 2.  Select the v2 generated
    # dialect before a connection is created; this also makes direct callers
    # of this compatibility helper decode the same wire format.
    if mavutil.mavlink.WIRE_PROTOCOL_VERSION != "2.0":
        environ["MAVLINK20"] = "1"
        mavutil.set_dialect("ardupilotmega")
    mavlink = mavutil.mavlink
    if PARAM_ERROR_MESSAGE_ID in mavlink.mavlink_map:
        return

    class MAVLinkParamErrorMessage(  # pylint: disable=too-few-public-methods
        mavlink.MAVLink_message
    ):  # type: ignore[misc]
        """MAVLink PARAM_ERROR message generated from common.xml."""

        id = PARAM_ERROR_MESSAGE_ID
        msgname = "PARAM_ERROR"
        fieldnames: ClassVar[list[str]] = ["target_system", "target_component", "param_id", "param_index", "error"]
        ordered_fieldnames: ClassVar[list[str]] = ["param_index", "target_system", "target_component", "param_id", "error"]
        fieldtypes: ClassVar[list[str]] = ["uint8_t", "uint8_t", "char", "int16_t", "uint8_t"]
        orders: ClassVar[list[int]] = [1, 2, 3, 0, 4]
        lengths: ClassVar[list[int]] = [1, 1, 1, 1, 1]
        array_lengths: ClassVar[list[int]] = [0, 0, 16, 0, 0]
        crc_extra: ClassVar[int] = 209
        unpacker: ClassVar[struct.Struct] = struct.Struct("<hBB16sB")
        native_format: ClassVar[bytearray] = bytearray(b"<hBB16sB")

        def __init__(  # pylint: disable=too-many-arguments,too-many-positional-arguments
            self,
            target_system: int,
            target_component: int,
            param_id: bytes | str,
            param_index: int,
            error: int,
        ) -> None:
            super().__init__(self.id, self.msgname)
            self._fieldnames = self.fieldnames
            self.target_system = target_system
            self.target_component = target_component
            self.param_id = (
                param_id.decode("ascii", errors="replace").rstrip("\x00")
                if isinstance(param_id, bytes)
                else param_id.rstrip("\x00")
            )
            self.param_index = param_index
            self.error = error

        def pack(self, mav: object, force_mavlink1: bool = False) -> bytes:
            """Serialize using the same implementation generated by pymavlink."""
            return self._pack(  # type: ignore[attr-defined]
                mav,
                self.crc_extra,
                self.unpacker.pack(
                    self.param_index,
                    self.target_system,
                    self.target_component,
                    self.param_id.encode("ascii"),
                    self.error,
                ),
                force_mavlink1=force_mavlink1,
            )

    mavlink.mavlink_map[PARAM_ERROR_MESSAGE_ID] = MAVLinkParamErrorMessage
    mavlink.MAVLINK_MSG_ID_PARAM_ERROR = PARAM_ERROR_MESSAGE_ID

    # Keep the enum values available to callers even when the installed pymavlink
    # dialect predates MAV_PARAM_ERROR.
    for value, name in enumerate(
        (
            "MAV_PARAM_ERROR_NO_ERROR",
            "MAV_PARAM_ERROR_DOES_NOT_EXIST",
            "MAV_PARAM_ERROR_VALUE_OUT_OF_RANGE",
            "MAV_PARAM_ERROR_PERMISSION_DENIED",
            "MAV_PARAM_ERROR_COMPONENT_NOT_FOUND",
            "MAV_PARAM_ERROR_READ_ONLY",
        )
    ):
        if not hasattr(mavlink, name):
            setattr(mavlink, name, value)


def get_param_error_message(message: object, param_name: str) -> int | None:
    """
    Return a matching PARAM_ERROR code, or ``None`` for another message.

    MAVLink parameter identifiers may contain no trailing null byte when they are
    exactly sixteen characters long, so matching is performed on the decoded value.

    """
    param_id = getattr(message, "param_id", None)
    error = getattr(message, "error", None)
    if isinstance(param_id, bytes):
        param_id = param_id.decode("ascii", errors="replace")
    if not isinstance(param_id, str) or not isinstance(error, int):
        return None
    return error if param_id.rstrip("\x00") == param_name else None
