name: Codespell

on:
  push:
    paths:
      - '**/*' # Run on all files
  workflow_dispatch:

permissions:
  contents: read

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run codespell
        uses: codespell-project/actions-codespell@406322ec52dd7b488e48c1c4b82e2a8b3a1bf630 # v2.1
        with:
          check_filenames: true
          check_hidden: true
          skip: '*.ipynb,*.svg,*.xml,*.pdef.xml,*.pdf,*.po,*.html,*.js,*.css' # Add file types/paths to skip
          # Optional: specify a custom dictionary
          # dictionary: .codespell/dictionary.txt
          # Optional: specify a codespell configuration file
          # codespell_args: --config .codespellrc
          # Optional: specify a list of words to ignore
          ignore_words_list: SITL,PARM,parm,NED,THST,intoto
          exclude_file: .codespell-exclude-file
