name: Codecov

on:
  push:
    paths:
      - '**/*.py'        # Watch for changes in any Python files
      - 'pyproject.yml'  # Watch for changes in the pyproject.yml file
  workflow_dispatch:
  release:
    types: [published]

jobs:
  pytests:
    uses: ./.github/workflows/pytest.yml  # use the callable pytest.yml workflow to run tests

  upload_coverage_to_codecov:
    runs-on: ubuntu-latest
    needs: pytests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report-3.9

      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          verbose: true
          files: tests/coverage-3.9.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
