name: Codecov

on:
  push:
    paths:
      - '**/*.py'        # Watch for changes in any Python files
      - 'pyproject.yml'  # Watch for changes in the pyproject.yml file
  workflow_dispatch:
  release:
    types: [published]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pymavlink pytest pytest-cov coverage mock
          pip install -U .

      - name: Install apt packages
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Run tests and collect coverage
        # run: pytest --cov ardupilot_methodic_configurator
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x16 &
          coverage run -m pytest
          coverage xml -o tests/coverage.xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v4.0.1
        with:
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
