name: gitavscan

on:
  push:
    paths:
      - '**/*.py'        # Watch for changes in any Python files
  release:
    types: [published]

permissions:
  contents: read  # Default limited permission

jobs:
  gitavscan:
    runs-on: ubuntu-latest
    name: AV scan

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Setup ClamAV configuration
      run: |
        sudo mkdir -p /etc/clamav
        echo 'TCPSocket 3310
        TCPAddr 127.0.0.1
        LocalSocket /var/run/clamav/clamd.sock
        User clamav
        LogFile /var/log/clamav/clamav.log
        LogTime yes
        LogVerbose yes
        PidFile /var/run/clamav/clamd.pid' | sudo tee /etc/clamav/clamd.conf
        sudo chmod 644 /etc/clamav/clamd.conf

    - name: Git AV Scan
      uses: djdefi/gitavscan@29c1c064ea648b71188b5c8155caef84ee50367b # main
