name: Pylint

on:
  pull_request:
    paths:
      - '**/*.py'        # Watch for changes in any Python files
      - 'pyproject.toml' # Watch for changes in the pyproject.toml file
  push:
    paths:
      - '**/*.py'        # Watch for changes in any Python files
      - 'pyproject.toml' # Watch for changes in the pyproject.toml file
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: ci-${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.14"]

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    # https://docs.astral.sh/uv/guides/integration/github/
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: true

    - name: Install dependencies
      # these extra packages are required by pylint to validate the python imports
      run: |
        uv pip install .[dev,scripts,pypi_dist]

    - name: Install ty dependency
      run: |
        uv pip install ty

    - name: Analyze the code with ty
      run: |
        ty check

    - name: Analyze the code with pylint
      run: |
        pylint $(git ls-files '**/*.py')
