name: Pylint

on:
  pull_request:
    paths:
      - '**/*.py'        # Watch for changes in any Python files
      - 'pyproject.toml' # Watch for changes in the pyproject.toml file
  push:
    paths:
      - '**/*.py'        # Watch for changes in any Python files
      - 'pyproject.toml' # Watch for changes in the pyproject.toml file
  workflow_dispatch:

concurrency:
  group: ci-${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.14"]

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    # https://docs.astral.sh/uv/guides/integration/github/
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: true

    - name: Install dependencies
      # these extra packages are required by pylint to validate the python imports
      run: |
        uv pip install .[dev,scripts,pypi_dist]

    - name: Install ty dependency
      run: |
        uv pip install ty

    - name: Analyze the code with ty
      run: |
        ty check

    - name: Analyze the code with pylint
      run: |
        pylint $(git ls-files '**/*.py')
