name: Python cleanliness

on: [push, pull_request, workflow_dispatch]

#concurrency:
#  group: ci-${{github.workflow}}-${{ github.ref }}
#  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python -m pip install -U ruff

      - name: Lint with Ruff
        run: |
          ruff check --output-format=github .
