name: Renovate SW dependencies

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:     # Allows manual trigger
  push:
    paths:
      - "renovate.json"  # Run when renovate config changes

permissions:
  contents: read  # Default limited permission

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Job-specific permission for creating branches
      pull-requests: write # Job-specific permission for creating PRs
      issues: write        # for creating dashboard issues
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@8217b3fc286df088d7c27f3255fe8414463bc0fd # v46.1.15
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: renovate.json
        env:
          LOG_LEVEL: debug
