name: Renovate SW dependencies

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:     # Allows manual trigger
  push:
    paths:
      - "renovate.json"  # Run when renovate config changes

permissions:
  contents: read  # Default limited permission

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Job-specific permission for creating branches
      pull-requests: write # Job-specific permission for creating PRs
      issues: write        # for creating dashboard issues
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@e09d604f8f803bb527bd8321ed5be06c460b8682 # v46.2.2
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: renovate.json
        env:
          LOG_LEVEL: debug
