name: Update Flight Controller IDs

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * 3'  # Every Wednesday at 1:30 AM

permissions:
  contents: read

jobs:
  update-ids:
    permissions:
      contents: write  # for Git to git push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout MethodicConfigurator
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Checkout ArduPilot
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: ArduPilot/ardupilot
          path: ardupilot

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install 'pip==25.0.1'
          mv ardupilot ..

      - name: Update flight controller IDs
        run: python update_flight_controller_ids.py

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add ardupilot_methodic_configurator/middleware_fc_ids.py
          if [ -n "$(git status --porcelain)" ]; then
            CHANGED_LINES=$(git diff --staged | grep -E "^[\+\-]" | wc -l)
            if [ $CHANGED_LINES -gt 3 ]; then
              git commit -m "chore(flightcontroller): Updated ArduPilot flight controller IDs [skip ci]"
              git push
            else
              echo "Not enough changes to commit (only $CHANGED_LINES lines changed)"
            fi
          else
            echo "No changes to commit"
          fi
